module.exports = {
    public:{
        dfParkName:{zh:'园叮智慧园区',en:'Garden Park Smart Park'},
        submit:{zh:'提交中',en:'submitting'},
        deleteTip:{zh:'删除中',en:'deleting'},
        sendTip:{zh:'发送中...',en:'sending...'},
        loadingTip:{zh:'加载中',en:'Loading'},
        saveTip:{zh:'保存中',en:'Preservation'},
        editSuccess:{zh:'修改成功!',en:'Successfully modified!'},
        sendSuccessTip:{zh:'发送成功',en:'Sent successfully'},
        collectTip: { zh: '已收藏', en: 'Collected' },
        callOffCollect:{zh:'取消收藏',en:'Cancel collection'},
        callOffCollectTip:{zh:'已取消收藏',en:'Collection has been canceled!'},
        scoredTip:{zh:'已评分',en:'Scored'},
        loginTimeout:{zh:'登录已超时，请重新登录再进行操作！',en:'The login has timed out, please log in again and proceed!'},
        loadingData:{zh:'数据加载中',en:'loading'},
        loadError:{zh:'数据加载失败',en:'Data loading failed'},
        warmPrompt:{zh:'温馨提示',en:'Tips'},
        startTimeTip:{zh:'请选择开始时间！',en:'Please choose the start time!'},
        endTimeTip:{zh:'请选择结束时间！',en:'Please select the end time!'},
        contactTip:{zh:'联系人不能为空！',en:"Contacts can't be empty!"},
        contactPhoneTip:{zh:'联系人手机号格式不正确！',en:'Contact phone number format is incorrect!'},
        phoneTip:{zh:'请输入正确的手机号格式',en:'Please enter the correct phone number format'},
        verifyCodeTip:{zh:'请输入验证码',en:'please enter verification code'},
        passwordTip:{zh:'请输入密码',en:'Please enter your password'},
        passwordTip2:{zh:'请输入6位以上的密码',en:'Please enter a password of 6 or more digits'},
        passwordTip3:{zh:'两次密码不一致',en:'Two passwords are inconsistent'},

        getCodeError:{zh:'获取验证码失败',en:'Failed to get verification code'},
        userTip:{zh:'请输入用户名',en:'please enter user name'},
        nameTip:{zh:'请输入您的姓名',en:'please enter your name'},
        registerSuccessTip:{zh:'注册成功',en:'registration success'},
        noDescriptionTip:{zh:'暂无描述',en:'No description'},

        writeInfo:{zh:'填写基本信息',en:'Fill in the basic information'},
        moreText:{zh:'上拉加载更多',en:'Pull up load more'},
        noMoreText:{zh:'没有更多了',en:'No more'},
        individual:{zh:'个',en:' '},
        yuanText:{zh:'元',en:' yuan'},
        zheText:{zh:'折',en:'% discount '},
        unread:{zh:'未读',en:'unread'},
        previewErrorTip:{zh:'图片预览失败',en:'Image preview failed'},
        saveImgSuccessTip:{zh:'已保存到相册',en:'Saved to album'},
        saveImgErrorTip:{zh:'图片保存失败',en:'Image save failed'},

        //input  placeholder提示
        contactPl:{zh:'请输入联系人',en:'Please enter a contact'},
        contactPhonePl:{zh:'请输入联系电话',en:'Please type your phone number'},
        phonePl:{zh:'请填写手机号码',en:'Please fill in cell phone number'},
        verifyCodePl:{zh:'填写验证码',en:'Fill in the verification code'},
        passwordPl:{zh:'请输入6位以上的密码',en:'Please enter a password of 6 or more digits'},
        verifyPasswordPl:{zh:'请再次输入密码',en:'Please enter your password again'},
        companyPl:{zh:'请填写企业名称',en:'Please fill in the company name'},
        namePl:{zh:'请输入真实姓名',en:'Please enter your real name'},
        myReplyPl:{zh:'请输入回复信息',en:'Please enter a response'},
        pleaseChoosePl:{zh:'请选择',en:'Please choose'},

         //表单字段
        companyName:{zh:'企业名称',en:'Company Name'},
        name:{zh:'姓名',en:'Name'},
        contact:{zh:'联系人',en:'Contact'},
        contactPhone:{zh:'联系电话',en:'CellPhone'},
        reserveDate:{zh:'预定日期',en:'Date'},
        reserveTime:{zh:'预定时间',en:'Time'},
        startTime:{zh:'开始时间',en:'Start'},
        endTime:{zh:'结束时间',en:'End'},
        order:{zh:'订单号',en:'Order'},
        orderCreateTime:{zh:'订单创建时间',en:'Creation time'},
        payTime:{zh:'支付时间',en:'Pay Time'},
        payWay:{zh:'支付方式',en:'Payment method'},
        sponsor:{zh:'主办方',en:'Organizer'},
        address:{zh:'地址',en:'Address'},
        time:{zh:'时间',en:'Time'},
        toText:{zh:'至',en:'To'},
        applyTime:{zh:'提交时间',en:'Submission Time'},
        phoneCode:{zh:'手机号码',en:'Cellphone'},
        verifyCode:{zh:'验证码',en:'Verification code'},
        password:{zh:'输入密码',en:'Password'},
        resetPassword:{zh:'重设密码',en:'Reset Password'},
        verifyPassword:{zh:'确认密码',en:'Confirm password'},
        imgAccessory:{zh:'图片附件',en:'Image attachment'},
        myReply:{zh:'我的回复',en:'My Reply'},
        useExplain:{zh:'使用说明',en:'Description'},
        today:{zh:'今天',en:'today'},
        month:{zh:'本月',en:'this month'},
        all:{zh:'全部',en:'all'},
        addAccessory:{zh:'添加附件',en:'Add attachments'},
        service:{zh:'客服',en:'Service'},
        consultationTip:{zh:'您正在咨询的是：',en:'What you are consulting is:'},
        remark:{zh:'备注信息',en:'Remark'},
        remarkNone:{zh:'无备注信息！',en:'No comments!'},
        payMoney:{zh:'支付金额',en:'Payment amount'},

        //按钮
        callOffBtn:{zh:'取消',en:'Cancel'},
        confirmBtn:{zh:'确定',en:'Confirm'},
        submitBtn:{zh:'立即提交',en:'Submit now'},
        submitBtn2:{zh:'提 交',en:'Submit'},
        reserveBtn:{zh:'立即预定',en:'Book now'},
        checkMoreBtn:{zh:'查看全部',en:'check all'},
        packUpBtn:{zh:'收起',en:'Collapse'},
        getCodeBtn:{zh:'获取验证码',en:'Get code'},
        getCodeBtn2:{zh:'重新获取',en:'Reacquire'},
        verifySubmitBtn:{zh:'确认提交',en:''},
        replyBtn:{zh:'回 复',en:'Confirm'},
        useBtn:{zh:'立即使用',en:'Reply'},
        backIndexBtn:{zh:'返回首页',en:'Back to home'},
    },

    //暂无字段
    nothingData:{
        activity:{zh:'目前还没有活动哦！',en:'There is no activity yet!'},
        activity_collect:{zh:'目前还没有收藏的活动哦！',en:'There are currently no collections!'},
        news:{zh:'目前还没有资讯哦！',en:'There is no information yet!'},
        news_collect:{zh:'目前还没有收藏的资讯哦！',en:'There is currently no collection of information!'},
        discuss:{zh:'还没有人评论！',en:'No one has commented yet!'},
        policy:{zh:'目前还没有政策哦！',en:'There are no policies yet!'},
        policy_collect:{zh:'目前还没有收藏的政策哦！',en:'There is currently no collection policy!'},
        supplies:{zh:'目前还没有借用记录哦！',en:'There are no borrowing records yet!'},
        order:{zh:'暂无订单！',en:'No orders!'},
        repair:{zh:'暂无报修信息！',en:'No repair information!'},
        reserve:{zh:'暂无预定场地！',en:'No reservations yet!'},
        expert:{zh:'暂无专家信息！',en:'No expert information!'},
        expert2:{zh:'目前还没有收藏的专家哦！',en:'There are no experts in the collection!'},
        message:{zh:'暂无通知消息！',en:'No notification message!'},
        visitor:{zh:'暂无预约信息！',en:'No reservation information!'},
        complaint:{zh:'暂无投诉信息！',en:'No complaint information!'},
        myRecommend:{zh:'暂无浏览记录！',en:'No browsing history!'},
        coupon_list:{zh:'暂无优惠券！',en:'No coupons!'},
        companyHosekeeper:{zh:'暂无企业管家',en:'No corporate steward'},
        companySearchList:{zh:'请搜索关键字查找企业！',en:'Please search keywords to find enterprises!'},
        serve:{zh:'暂无服务',en:'No services'},
        backIndexBtn:{zh:'返回首页',en:'Back to home'},
    },

    //结果页
    result:{
        nothing:{
            page_title:{zh:'暂无内容',en:'No content'},
            title:{zh:'暂无内容！',en:'No content yet!'}
        },
        reg:{
            page_title:{zh:'注册成功',en:'Registration success'},
            title:{zh:'恭喜！注册成功！',en:'Congratulations! registration success!'},
            btm_btn:{zh:'进入首页',en:'Enter to home'}
        },
        reset_pwd:{
            page_title:{zh:'重置密码成功',en:'Reset password successfully'},
            title:{zh:'恭喜！重设密码成功！',en:'Congratulations! Reset password successfully!'},
            btm_btn:{zh:'返回登录界面',en:'Return to the login screen'}
        },
        venue:{
            page_title:{zh:'场地预定',en:'Site reservation'},
            title:{zh:'场地预定申请已提交！',en:'The venue has been booked successfully!'},
            des:{zh:'待物业人员审核通过后即可成功预定',en:'The reservation can be made successfully after the approval of the property management personnel'},
            details_btn: {zh:'查看预定订单 >>',en:'View scheduled order >>'},
        },
        pay:{
            page_title:{zh:'支付成功',en:'Payment successful'},
            title:{zh:'支付成功',en:'Payment successful'},
            details_btn: {zh:'查看订单 >>',en:'check order >>'},
        },
        pay_venue:{
            page_title:{zh:'支付成功',en:'Payment successful'},
            title:{zh:'支付成功',en:'Payment successful'},
            details_btn:{zh:'返回我的预定 >>',en:'Return to my reservation >>'}
        },
        wuzi:{
            page_title:{zh:'物资共享',en:'Material sharing'},
            title:{zh:'您的需求申请已提交成功',en:'Your request has been submitted.'},
            des:{zh:'待物业人员审核完成即可成功借用',en:'Successful loan can be made upon completion of property personnel audit.'},
            details_btn:{zh:'查看租用记录 >>',en:'View rental history >>'}
        },
        repair:{
            page_title:{zh:'在线报修',en:'Online repair'},
            title:{zh:'报修申请已成功提交',en:'The application for repair has been successfully submitted'},
            des:{zh:'我们已收到您的报修，将会有专人联系您，\n请保持手机畅通',en:'We have received your application for repairs. We will have someone to contact you. Please keep your cell phone open.'},
            details_btn:{zh:'查看报修订单 >>',en:'View newspaper revision >>'}
        },
        activity:{
            page_title:{zh:'报名成功',en:'Successful registration'},
            title:{zh:'报名成功',en:'Successful registration'},
            details_btn:{zh:'查看报名详情 >>',en:'View registration details >>'}
        },
        complaint:{
            page_title:{zh:'提交成功',en:'Submitted successfully'},
            title:{zh:'提交成功！',en:'Submitted successfully！'},
            details_btn:{zh:'查看历史记录 >>',en:'View history >>'}
        },
        recommend:{
            page_title:{zh:'预约成功',en:'Successful appointment'},
            title:{zh:'预约成功！',en:'Successful appointment！'},
        },
        coupon:{
            page_title:{zh:'使用优惠券',en:'Coupon'},
            title:{zh:'用券成功！',en:'Successful use of coupons！'},
            details_btn:{zh:'我的优惠券列表 >>',en:'My coupon list >>'}
        },
        serveOrder:{
            page_title:{zh:'下单成功',en:''},
            title:{zh:'下单成功！',en:''},
            des:{zh:'请保持联系方式畅通，以便工作人员进行联系。',en:''},
            details_btn:{zh:'查看订单 >>',en:''},
            btm_btn:{zh:'返回服务首页',en:''}
        },
        serveConsult:{
             page_title:{zh:'提交成功',en:''},
            title:{zh:'您的咨询已提交！',en:''},
            des:{zh:'请保持联系方式畅通，以便工作人员进行联系。',en:''},
            btm_btn:{zh:'返回服务首页',en:''}
        },
        serveCancel:{
            page_title:{zh:'取消服务',en:''},
            title:{zh:'提交成功',en:''},
            des:{zh:'',en:''},
            details_btn:{zh:'查看订单 >>',en:''},
            btm_btn:{zh:'返回服务首页',en:''}
        },
        backIndexBtn:{zh:'返回首页',en:'Back to home'}
    },

    //验证
    validate:{
        empty:{zh:'不能为空',en:"Can't be empty"},
        phone:{zh:'手机号格式有误',en:'The format of mobile phone number is incorrect'},
        email:{zh:'邮箱格式有误',en:'Error in mailbox format'},
        verifyCodeEmpty:{zh:'验证码不能为空',en:'Verification code cannot be empty'},
        password:{zh:'请输入6位以上密码',en:'Please enter more than 6 passwords'},
        passwordAgain:{zh:'请再次输入密码',en:'Please enter your password again.'},
        passwordContrast:{zh:'两次密码不一致',en:'Two password inconsistencies'},
        userName:{zh:'请输入用户名',en:'Enter one user name'},
        park:{zh:'请选择园区',en:'Please choose the park.'},
        ent:{zh:'请选择企业',en:'Please choose the enterprise'},
        name:{zh:'请输入您的名字',en:'Please enter your name.'},
        date:{zh:'请选择预约日期',en:'Please choose the appointment date.'},
        time:{zh:'请选择预约时间',en:'Please choose the appointment time.'},
    },

    //首页
    index:{
        indexTitle:{zh:'园叮智慧园区',en:'Garden Park Smart Park'},
        noticeImg:{zh:'notice_tit.png',en:'notice_tit_en.png'},
        menu:{
            repair:{zh:'在线报修',en:'Repair'},
            order:{zh:'账单查询',en:'Order'},
            venue:{zh:'场地预定',en:'Reservation'},
            policy:{zh:'热门政策',en:'Policy'},
            recommend: { zh: '推荐有礼', en: 'Recommend' },
            supplies:{zh:'物资共享',en:'Goods'},
            steward:{zh:'企业管家',en:'Steward'},
            scanCode:{zh:'扫码开门',en:'Scan Code'},
            zgjApp:{zh:'羊城招管家',en:'Yangcheng'},
            activity:{zh:'活动中心',en:'Activity'},
            parking: { zh: '月保缴费', en: 'Parking' },
            news:{zh:'新鲜事',en:'News'},
            companyNews:{zh:'企业名录',en:'Directories'},
            visitor:{zh:'访客预约',en:'Visitor'},
            orderfood:{zh:'在线订餐',en:'Food Online'},
            coupon:{zh:'领券中心',en:'Coupon'},
            complaint:{zh:'投诉建议',en:'Complaint'},
        },
        defaultParkText:{zh:'园叮智慧园区',en:'Garden Park Smart Park'},
        newText:{zh:'最新',en:'new'},
        recentText:{zh:'近期',en:'recent'},
        moreText:{zh:'更多 >',en:'more >'},
        backlogTitle:{zh:'待办事项',en:'To-do'},
        repairText:{zh:'报修',en:'repair'},
        goodsText:{zh:'物资',en:'good'},
        billText:{zh:'账单',en:'order'},
        costText:{zh:'费用',en:'cost'},
        fixturesText:{zh:'装修',en:'decoration'},
        pending:{zh:'待处理',en:'pending'},
        houseTitle: { zh: '招商一览', en: '' },
        unitPrice: { zh: ' 元/㎡', en: '' },
        policyTitle:{zh:'申报政策',en:'Policy'},
        successRateText:{zh:'成功率',en:'Success rate'},
        highestText:{zh:'最高',en:'highest'},
        activityTitle:{zh:'热门活动',en:'Hot Activity'},
        lineBooksTitle:{zh:'线上图书',en:'Books Online'},
        jurisdictionTip:{zh:'需要企业审核认证通过才能使用此功能！',en:'Enterprise audit and certification is required to use this function!'},
        buildTip:{zh:'功能建设中',en:'Construction in progress'}
    },

    //发现首页
    foundIndex:{
        foundTitle:{zh:'发现',en:'Found'},
        companyNews: { zh: '企业名录', en: 'Directories' },
        tagNews:{zh:'新鲜事',en:'News'},
        tagPolicy:{zh:'最新政策',en:'New Policy'},
        moreText:{zh:'更多 >',en:'More >'},
        recommendTitle:{zh:'为你推荐',en:'Recommend'},
        //行业专家
        expertTitle:{zh:'行业专家',en:'Industry Expert'},
        projectText:{zh:'已指导项目',en:'Guided Project'},
        geText:{zh:'个',en:''},
        referText:{zh:'在线咨询',en:'Consultation'},
        //专家详情
        expertDetailTag:[
            {zh:'专家简介',en:'Intro'},
            {zh:'经历描述',en:'Description'},
            {zh:'主要成就',en:'Achievement'}
        ],
        referText2:{zh:'立即咨询',en:'Consult'},
        attentionBtn:{zh:'关注',en:'attention'},
        collectText:{zh:'已收藏！',en:'collected！'},
        unCollectText:{zh:'已取消收藏！',en:'Collection cancelled！'},
    },

    //政策
    policyDetail:{
        title01:{zh:'您的企业成功通过率为',en:'Your business success rate'},
        bestText:{zh:'最高',en:'highest'},
        yuan:{zh:'元',en:'yuan'},
        noText:{zh:'无',en:'--'},
        cutOffTime:{zh:'截止时间',en:'deadline'},
        condition:{zh:'项条件达标',en:'condition is met'},
        unCondition:{zh:'项条件不达标',en:'condition is not satisfied'},
        checkDetailBtn:{zh:'查看详情 >>',en:'see details >>'},
        title02:{zh:'政策原文',en:'Original policy'},
        issueText:{zh:'发布于',en:'Date'},
        accessoryArea:{zh:'附件区',en:'Accessory area'},
        accessory:{zh:'附件',en:'annex'},
        original:{zh:'访问原文链接',en:'Visit the original link'},
        copyTip:{zh:'原文链接已复制',en:'The original link has been copied'},
        referBtn:{zh:'立即咨询',en:'Consult'},
        collectBtn:{zh:'收藏',en:'Collect'},
        assessBtn:{zh:'立即评估',en:'Immediate assessment'},
        subject:{zh:'主题',en:'theme'},
        conditionStatus:{zh:'达标状态',en:'Compliance status'},
        applyTitle:{zh:'项目申报系统',en:'Project declaration system'}
    },

    //服务
    services:{
        title:{zh:'服务',en:'Services'},
        moreBtn:{zh:'更多 >',en:'More >'},
        referBtn:{zh:'在线咨询',en:'Consult'},
        
    },

    //我的页面
    userIndex:{
        title:{zh:'个人中心',en:'My'},
        editBtn:{zh:'编辑资料',en:'Edit Information'},
        repairBtn:{zh:'我的报修',en:'My repair'},
        venueBtn:{zh:'我的预定',en:'My reserve'},
        invoiceBtn:{zh:'我的发票',en:'My nvoice'},
        recommendBtn:{zh:'推荐有礼',en:'Recommend'},
        changeLangBtn:{zh:'切换语言',en:'Language'},
        couponBtn:{zh:'卡券包',en:'My coupon'},
        collectBtn:{zh:'我的收藏/关注',en:'My collect'},
        activityBtn:{zh:'我的活动',en:'My activity'},
        orderBtn:{zh:'我的订单',en:'My order'},
        borrowedBtn:{zh:'我的物资',en:'My borrowed'},
        serveBtn:{zh:'我的服务',en:'My services'},
        complaintBtn:{zh:'我的投诉',en:'My complaint'},
        recommendBtn2:{zh:'我的推荐',en:'My recommend'},
        changeGardenBtn:{zh:'切换园区',en:'Change Park'},
        discussBtn:{zh:'我的评论',en:'My discuss'},
        buildBtn:{zh:'建设中...',en:'in construction...'},
    },

    //用户信息页
    userInfo:{
        title:{zh:'个人资料',en:'personal information'},
        park:{zh:'园区',en:'Park'},
        name:{zh:'真实姓名',en:'Actual Name'},
        realName:{zh:'实名认证',en:'Verified'},
        nickName:{zh:'昵称',en:'Nickname'},
        inputNickName:{zh:'输入昵称',en:'Enter nickname'},
        sex:{zh:'性别',en:'Sex'},
        sexList:[
            {zh:'保密',en:'confidentiality'},
            {zh:'男',en:'man'},
            {zh:'女',en:'woman'},
        ],
        phone:{zh:'手机号码',en:'Cellphone'},
        bindPhone:{zh:'手机号码',en:'Binding phone'},
        email:{zh:'邮箱地址',en:'Email'},
        bindEmail:{zh:'绑定邮箱',en:'Bind mailbox'},
        outLogin:{zh:'退出登录',en:'Sign out'},
        versions:{zh:'当前版本',en:'current version'},
        outTipTitle:{zh:'退出登录',en:'Sign out'},
        outTipAlert:{zh:'退出系统后将不能接收各种通知，\n仍然退出？',en:'You will not receive various notifications when you log out of the system,Still exiting?'},
        editSuccessTip:{zh:'修改成功！',en:'Modified success'},
        editTip:{zh:'修改中',en:'revised'},
        outTip:{zh:'退出中',en:'Exiting'},
    },


    //服务
    updataInfo:{
        name:{
            pageTitle:{zh:'修改姓名',en:'Change name'},
            title:{zh:'姓名',en:'Name'},
            placeholderText:{zh:'请输入你的姓名',en:'Please enter your name'},
            tipText:{zh:'请不要含有特殊字符，比如“#”“@”等等',en:'Please do not include special characters such as "#" "@", etc.'},
        },
        nickname:{
            pageTitle:{zh:'修改昵称',en:'Change Nickname'},
            title:{zh:'昵称',en:'Nickname'},
            placeholderText:{zh:'请输入你的昵称',en:'Please enter your nickname'},
            tipText:{zh:'请不要含有特殊字符，比如“#”“@”等等',en:'Please do not include special characters such as "#" "@", etc.'},
        },
        cellphone:{
            pageTitle:{zh:'修改手机号',en:'Modify phone number'},
            title:{zh:'手机号',en:'phone'},
            placeholderText:{zh:'请输入你的手机号码',en:'Please enter your mobile number'},
            tipText:{zh:'请输入11位数字',en:'Please enter 11 digits'},
        },
        email:{
            pageTitle:{zh:'修改邮箱地址',en:'Modify email address'},
            title:{zh:'邮箱地址',en:'Email'},
            placeholderText:{zh:'请输入你的邮箱地址',en:'Please enter your email address'},
            tipText:{zh:'请输入正确格式的邮箱地址',en:'Please enter the correct format email address'},
        },
    },

    //活动
    activity:{
        myActTitle:{zh:'我报名的活动',en:'My activity'},
        listTitle:{zh:'活动中心',en:'Activity'},
        listTitle2:{zh:'已报名的活动',en:'Registered event'},
        actApplayTitle:{zh:'活动报名',en:'event registration'},
        checkApplyTitle:{zh:'查看报名信息',en:'View registration information'},
        status1:{zh:'准备中',en:'preparing'},
        status2:{zh:'报名中',en:'registration'},
        status3:{zh:'待开始',en:'waiting to start'},
        status4:{zh:'进行中',en:'processing'},
        status5:{zh:'已结束',en:'end'},
        free:{zh:'免费',en:'free'},
        applyText:{zh:'人已报',en:'applicants'},
        actDetail:{zh:'活动详情',en:'Details of the event'},
        rule:{zh:'活动规则',en:'Rule Of Activity'},
        detailTitle:{zh:'活动详情',en:'Details Of The Event'},
        applyInfo:{zh:'报名信息',en:'register information'},
        returnActDetail:{zh:'返回',en:'Return to event details'},
    },

    //企业管家
    companyHousekeeper:{
        title:{zh:'企业管家',en:'Business Housekeeper'},
    },

    //收藏关注页面
    collect:{
        title:{zh:'收藏/关注',en:'Collection / attention'},
        actName:{zh:'活动',en:'Activity'},
        newsName:{zh:'资讯',en:'News'},
        policyName:{zh:'政策',en:'Policy'},
        expertName:{zh:'专家',en:'Expert'},
        popDes:{zh:'是否取消收藏该',en:'Whether to cancel the collecion'},
    },

    //报修
    repair:{
        //我的报修
        myRepairTitle:{zh:'我的报修',en:'My repair'},
        repairDetailTitle:{zh:'报修详情',en:'Repair details'},
        tagName1:{zh:'待处理',en:'Processed'},
        tagName2:{zh:'跟进中',en:'Following'},
        tagName3:{zh:'已完成',en:'Completed'},
        applyTime:{zh:'报修申请提交时间',en:'Repair application submission time'},
        repairType:{zh:'报修类型',en:'Repair type'},
        serveScore:{zh:'服务评分',en:'Service rating'},
        progressDetail:{zh:'进度详情',en:'Progress details'},
        repairInfo:{zh:'报修内容',en:'Repair content'},
        room:{zh:'房间',en:'Room'},
        severPopBtn:{zh:'有偿服务价格一览表 >>',en:'Paid service price list >>'},
        callOffBtn:{zh:'取消申请',en:'Cancel'},
        payMoney:{zh:'支付金额',en:'Payment amount'},
        affirmTitle:{zh:'取消',en:'Cancel'},
        affirmDes:{zh:'真的要取消报修订单吗？',en:'Do you really want to cancel the amendment?'},
        //在线报修
        repairTitle:{zh:'在线报修',en:'Online repair'},
        repairInfo:{zh:'报修内容',en:'Repair content'},
        repairDesPl:{zh:'请简短描述问题，限80字',en:'Please briefly describe the problem, limited to 80 words'},
        repairInfoTitle:{zh:'报修地点/联系人',en:'Repair location/contact'},
        chooseRoom:{zh:'选择房间',en:'Room'},
        repairBtn:{zh:'立即报修',en:'Immediate repair'},
        noRepairTip:{zh:'企业未认证，暂未能报修！',en:'The company has not been certified, and it has not been repaired yet!'},
        repairTypeTip:{zh:'请选择报修类型！',en:'Please choose the type of repair!'},
        repartRoomTip:{zh:'请选择房间号！',en:'Please select the room number!'},
        contactTip:{zh:'请输入联系人姓名！',en:'Please enter a contact name!'},
        phoneTip:{zh:'请输入正确的手机号格式！',en:'Please enter the correct phone number format!'},
        submitRepairTip:{zh:'提交报修中',en:'Submitted for repair'},
    },

    //场地预定
    reserve:{
        reserveTitle:{zh:'场地预定',en:'Site reservation'},
        myReserveTitle:{zh:'我的预定',en:'My reservation'},
        tagName1:{zh:'待确认',en:'Pending'},
        tagName2:{zh:'已通过',en:'Passed'},
        tagName3:{zh:'已过期',en:'Expired'},
        statusName1:{zh:'待确认',en:'Pending'},
        statusName2:{zh:'已确认',en:'confirmed'},
        labelName1:{zh:'待确认',en:'unconfirmed'},
        labelName2:{zh:'待支付',en:'unpaid'},
        labelName3:{zh:'已完成',en:'finish'},
        labelName4:{zh:'已过期',en:'expired'},
        labelName9:{zh:'未通过',en:'failed'},
        ydcdText:{zh:'预定场地',en:'Booking venue'},
        accommodate:{zh:'可容纳',en:'Can accommodate'},
        person:{zh:'人',en:'people'},
        bookingInfo:{zh:'预定信息',en:'Booking information'},
        yuan:{zh:'元',en:' yuan'},
        hour:{zh:'小时',en:'hour'},
        timeTip:{zh:'结束时间不能小于开始时间！',en:'The end time cannot be less than the start time!'},
        writeReserveInfo:{zh:'填写预约信息',en:'Fill in the reservation information'},
        reserveText1:{zh:'/小时，共',en:' / hour,'},
        reserveText2:{zh:'小时，前',en:' hours in total.The first '},
        reserveText3:{zh:'小时免费。',en:' hours are free. '},
        reserveText4:{zh:'需支付',en:'Need to pay '},
        reserveText5:{zh:'已支付',en:'Payment of '},
        reserveBtn:{zh:'立即预定',en:'Reserve'},
        timeTip1:{zh:'请选择开始时间！',en:'Please choose the start time!'},
        timeTip2:{zh:'请选择结束时间！',en:'Please choose the end time!'},
        dayNames:[
            {zh:'日',en:'Sun'},
            {zh:'一',en:'Mon'},
            {zh:'二',en:'Tues'},
            {zh:'三',en:'Wed'},
            {zh:'四',en:'Thur'},
            {zh:'五',en:'Fri'},
            {zh:'六',en:'Sat'},
        ],
        today:{zh:'今天',en:'today'},
        tomorrow:{zh:'明天',en:'tomorrow'},
        venueBtn:{zh:'提交预定信息',en:'Submit'},
        payBtn:{zh:'立即支付',en:'Pay'},
    },

    //物资共享
    supplies:{
        borrowTitle:{zh:'物资共享',en:'Material sharing'},
        borrowedRecordTitle:{zh:'借用记录',en:'Borrowing record'},
        borrowText:{zh:'借用',en:'borrow'},
        borrowStatus1:{zh:'申请中',en:'application'},
        borrowStatus2:{zh:'出借中',en:'lending'},
        borrowStatus4:{zh:'已归还',en:'returned'},
        borrowStatus5:{zh:'已拒绝',en:'rejected'},
        serveExplain:{zh:'服务说明',en:'Service Description'},
        explainDes:{zh:'园区内免费提供共享物资，在线申请即可获得使用权，数量有限，请大家按需申请，用完后请尽快归还，以方便他人借用。',en:'The shared materials are provided free of charge in the park. The right to use can be obtained by online application. The number is limited. Please apply as required. Please return it as soon as possible after use to facilitate borrowing.'},
        residue:{zh:'剩余',en:'Remaining'},
        borrowing:{zh:'借用中',en:'Borrowing'},
        applyBtn:{zh:'详细',en:'Application'},
        checkBorrowBtn:{zh:'查看借用记录 >>',en:'View borrowing records >>'},
        verifyBtn: { zh: '物品明细', en:'Item details'},
        popText01: { zh: '确认借用该物品？', en:'Are you sure you want to borrow this item?'},
        applyTip:{zh:'申请中',en:'applying'},
        confirmBtn: { zh: '借用', en: 'Borrow' },
    },

    //切换园区
    gardenChange:{
        title:{zh:'切换园区',en:'Switching Park'},
        curPark:{zh:'当前园区',en:'Current Park'},
        address:{zh:'地址',en:'Address'},
        allPark:{zh:'全部园区',en:'All Parks'},
        changeTip:{zh:'切换园区中',en:'Park switching'},
    },

    //注册登录
    formPage:{
        findPasswordTitle:{zh:'找回密码',en:'Retrieve password'},
        loginTitle:{zh:'登录',en:'Login'},
        registerTitle:{zh:'注册',en:'Register'},
        loginHeadTitle: { zh: '园叮智慧园区管理系统', en:'Yuanding intelligent park management system'},
        forgetPassword:{zh:'忘记密码',en:'forget password'},
        loginText1:{zh:'还没有账号？',en:"Don't have an account yet?"},
        quickregister:{zh:'快速注册',en:'Quick registration'},
        loginBtn:{zh:'立即登录',en:'Login'},
        userPl:{zh:'手机号',en:'Mobile phone'},
        passwordPl:{zh:'密码',en:'password'},
        regText1:{zh:'已有账号',en:'Existing account'},
        curPark:{zh:'所属园区',en:'Park'},
        company:{zh:'所属企业',en:'Company'},
        changeParkTip:{zh:'请选择所属园区',en:'Please select your own campus'},
        changeParkTip2:{zh:'请先选择园区！',en:'Please choose the park first!'},
        changeCompanyTip:{zh:'请选择所属企业',en:'Please select your company'},
        changePark:{zh:'选择园区',en:'Choose a park'},
        changeCompany:{zh:'选择企业',en:'Choose a company'},
        searchKey:{zh:'搜索关键字',en:'Search keywords'},
    },

    //投诉建议
    complaint:{
        title:{zh:'投诉建议',en:'Suggestions'},
        tagName01: { zh: '待处理', en: '' },
        tagName02: { zh: '处理中', en: '' },
        tagName03: { zh: '已完成', en: '' },
        subject:{zh:'主题',en:'subject'},
        subjectPl:{zh:'请填写主题',en:'Please fill in the subject'},
        subjectTip:{zh:'请输入主题！',en:'Please enter the subject!'},
        feedback:{zh:'反馈结果',en:'Feedback'},
        feedbackPl:{zh:'请输入您的反馈描述…',en:'Please enter your feedback description...'},
        feedbackTip:{zh:'请输入反馈内容！',en:'Please enter feedback!'},
        addPicBtn:{zh:'添加图片',en:'Add pictures'},
        checkRecordBtn:{zh:'查看历史记录 >>',en:'View history >>'},
        status1:{zh:'待指派',en:'Unassigned'},
        status2:{zh:'已指派',en:'Assigned'},
        status3:{zh:'处理中',en:'Processing'},
        status4:{zh:'已完成',en:'Completed'},
        applyTime:{zh:'发起时间：',en:'Apply Time'},
        processTime:{zh:'受理时间：',en:'Process Time'},
        finishTime:{zh:'完成时间：',en:'Finish Time'},
    },

    //优惠券
    coupon:{
        title:{zh:'优惠券',en:'Coupon'},
        listTitle:{zh:'领券中心',en:'Coupon'},
        useTitle:{zh:'使用优惠券',en:'Use a coupon'},
        getTime:{zh:'领取时间',en:'Pick up time'},
        free:{zh:'免费',en:'Free'},

        detailInfo:{zh:'详细信息',en:'Details'},
        issueTime:{zh:'领取时间',en:'Pick up time'},
        validTime:{zh:'生效时间',en:'ValidTime'},
        couponCode:{zh:'优惠券码',en:'Coupon code'},
        useTime:{zh:'使用时间',en:'Usage time'},
        manText:{zh:'满',en:'Full'},
        jianText:{zh:'减',en:''},
        text1:{zh:'元立减',en:'less'},
        text2:{zh:'元使用',en:'use'},
        text3:{zh:'无条件使用',en:'Unconditional use'},
        text4:{zh:'元立打',en:''},
        text5:{zh:'领券',en:'Ticket for '},
        text6:{zh:'天内',en:' days'},
        text7:{zh:'开始',en:''},
        yqText:{zh:'已抢',en:' already'},
        lqBtn:{zh:'立即领取',en:'Receive'},
        myCouponBtn:{zh:'我的卡券包 >>',en:'My card package >>'},
        lqSuccess:{zh:'领券成功',en:'Successful receipt'},
        popText1:{zh:'恭喜，优惠券已领取成功',en:'Congratulations, the coupon has been successfully received.'},
        popText2:{zh:'并已放到您的账户',en:'And put it in your account'},
        popUseBtn:{zh:'去使用',en:'Go to use'},

        startTime:{zh:'领取时间:',en:'Pick up time:'},
        endTime:{zh:'结束时间:',en:'End Time:'},
        pastDue:{zh:'过期:',en:'Expired'},

        status1:{zh:'即将开始',en:'unstarted'},
        status2:{zh:'领取中',en:'receiving'},
        status3:{zh:'已领完',en:'finished'},
        status4:{zh:'已过期',en:'expired'},
        btnName1:{zh:'立即使用',en:'use'},
        btnName2:{zh:'已使用',en:'Used'},
        btnName3:{zh:'已过期',en:'expired'},
        tagName1:{zh:'未使用',en:'Unused'},
        tagName2:{zh:'已使用',en:'Used'},
        tagName3:{zh:'已失效',en:'expired'},
    },

    //通知消息
    message:{
        listTitle:{zh:'通知消息',en:'Notification message'},
        noticeTitle:{zh:'通知公告',en:'Notice'},
    },

    //订单
    order:{
        title:{zh:'账单查询',en:'Billing Inquiry'},
        confirInfoTitle:{zh:'确认信息',en:'Confirmation information'},
        feePeriod:{zh:'计费月份',en:'Billing month'},
        feeProject:{zh:'计费项目',en:'Billing item'},
        detailBtn:{zh:'详情 >',en:'Details >'},
        money:{zh:'金额',en:'Amount'},
        payer:{zh:'付款方',en:'Payer'},
        payee:{zh:'收款方',en:'Beneficiary'},
        payText1:{zh:'共',en:'A total of'},
        payText2:{zh:'个缴费项目，需支付',en:'payment items, payable'},
        payBtn:{zh:'立即支付',en:'pay immediately'},
        signForBtn: { zh: '签收', en: 'Sign for' },

        //缴费详情
        costDetailTitle:{zh:'费用详情',en:'Fee details'},
        costTip:{zh:'请于每月5日前缴纳以下费用，逾期按每日5‰收取滞纳金',en:'Please pay the following fees before the 5th of each month. Late payment is charged at 5 baht per day.'},
        costDetail:{zh:'缴费项目明细',en:'Payment item details'},
        shouldCost:{zh:'应缴费用',en:'Payable fee'},
        month:{zh:'计费月份',en:'Billing month'},
        room:{zh:'房间',en:'room'},
        priceName:{zh:'单价',en:'unit price'},
        unitPrice:{zh:'元/平方米',en:'yuan / square meter'},
        countName:{zh:'面积',en:'area'},
        unitCount:{zh:'平方米',en:'㎡'},
        prevMeter:{zh:'上次抄表',en:''},
        currentMeter:{zh:'本次抄表',en:''},
        prevReading:{zh:'上月读数',en:''},
        currentReading:{zh:'本月读数',en:''},
        sharedFee:{zh:'本月公摊',en:''},
        realityCount:{zh:'实际用量',en:''},
        checkPic:{zh:'查看照片 >',en:'View photo >'},
        fangUnit:{zh:'方',en:'party'},
        duUnit:{zh:'度',en:''},
        month2: { zh:'月份',en:''},
        //订单列表
        orderTagName1:{zh:'待支付',en:'Unpaid'},
        orderTagName2:{zh:'未开票',en:'Unbilled'},
        orderTagName3:{zh:'全部',en:'All'},
        orderName:{zh:'账单',en:'Bill'},
        orderText1:{zh:'月份房租水电账单',en:'rent water and electricity bill'},
    },

    //房源推荐、
    recommend:{
        referrerTitle:{zh:'身份验证',en:'Authentication'},
        shareEwmTitle:{zh:'推广二维码',en:'Promote QR code'},
        recordTitle:{zh:'推荐记录',en:'Recommended record'},
        indexTitle:{zh:'推荐有礼',en:'Recommended gift'},
        subscribeTitle:{zh:'预约参观',en:'Make an appointment'},
        subscribeDate:{zh:'预约日期',en:'subscribe Date'},
        subscribeDatePl:{zh:'请选择拜访日期',en:'Please select a date of visit'},
        subscribeTime:{zh:'预约时间',en:'Appointment'},
        subscribeTimePl:{zh:'请选择拜访时间',en:'Please select the time of visit'},
        subscribeBtn:{zh:'立即预约',en:'Reservation Now'},

        //推荐首页
        ruleTitle:{zh:'活动规则说明',en:'Activity rule description'},
        quesList:[
            {
                title:{zh:'1、园叮是做什么的？房源分销是什么？',en:'1. What does the garden do? What is the distribution of properties?'},
                answer:{zh:'园叮是为孵化器、双创空间、中小产业园区等提供一站式企业服务的平台。房源分销，即您可以把园区房源直接推荐给您的好友，好友通过推荐链接或二维码成功入驻园区，您即可获得奖励！',en:'Garden is a platform for one-stop enterprise services for incubators, dual-creation spaces, small and medium-sized industrial parks. Listing distribution, you can directly recommend the park listing to your friends, friends can successfully enter the park through the recommended link or QR code, you can get rewards!'},
            },
            {
                title:{zh:'2、怎么成为推荐人？',en:'2. How to become a recommender？'},
                answer:{zh:'您只要输入手机号码及手机验证码进行注册，验证通过后，您便成为推荐人。',en:'You only need to enter your mobile phone number and mobile phone verification code to register. Once the verification is passed, you will become a referrer.'},
            }, 
            {
                title:{zh:'3、推荐人获得的奖励怎么计算？',en:'3. How is the reward obtained by the recommender calculated?'},
                answer:{zh:'如好友通过推荐人链接进驻推荐园区，推荐人即可获得奖励。',en:'If a friend enters the recommendation park through the referrer link, the referrer can receive the reward.'},
            }, 
            {
                title:{zh:'4、推荐有效期是多久？',en:'4. How long is the recommended validity period?'},
                answer:{zh:'从注册成功之日起，客户一年内签约成功推荐人便可获得推荐奖励。',en:'From the date of successful registration, the client can get a referral reward by signing a successful referee within one year.'},
            }, 
        ],
        recommendBtn:{zh:'立即推荐',en:'Recommend now'},
        //详情
        homeText:{zh:'首页',en:'Home'},
        detailTitle:{zh:'房源详情',en:'Listing details'},
        totalArea:{zh:'总面积',en:'Total area'},
        nowPrice:{zh:'当前在租价格',en:'Current rent price'},
        detailText1:{zh:'人浏览过该园区',en:' people viewed the park'},
        parkType:{zh:'园区户型',en:'Park type'},
        serveFacility:{zh:'服务及设施',en:'Services and facilities'},
        recentActivity:{zh:'近期活动',en:'recent activities'},
        parkIntro:{zh:'园区简介',en:'Park Introduction'},
        traffic:{zh:'公共交通',en:'Public transit'},
        tjBtnText1:{zh:'马上推荐，得',en:'Recommend now, get '},
        tjBtnText2:{zh:'元奖金',en:' yuan bonus'},
        kefuBtn:{zh:'咨询客服',en:'Advisory Service'},
        yycgBtn:{zh:'预约参观',en:'Make an appointment'},
        wyytjBtn:{zh:'我也要\n推荐',en:'recommend'},
        myshareBtn:{zh:'我的\n分享',en:'my\nshare'},
        authentication:{zh:'授权认证',en:'Authorized certification'},
        authenticationDes:{zh:'您需要进行授权后才能参与分享\n哦，赶紧授权拿佣金',en:'You need to authorize before you can participate in the sharing, and quickly authorize the commission.'},
        authenticationBtn:{zh:'好的，去授权',en:'Ok, go to authorize'},
        allHouseBtn: { zh: '所有户型 >', en:'All units'},
        //推广记录
        dataBrowse:{zh:'数据总览',en:'Data overview'},
        browseNum:{zh:'浏览人数',en:'Number of visitors'},
        consultNum:{zh:'咨询人数',en:'Number of consultants'},
        recordTrace:{zh:'客户记录追踪',en:'Customer record tracking'},
        tipText1:{zh:'通过二维码查看您的推荐信息',en:'View your recommendations via QR code'},
        checkRecord:{zh:'查看全部记录 >>',en:'View all records >>'},
        //推广记录列表
        recordTagName1:{zh:'按时间排序',en:'Time sorting'},
        recordTagName2:{zh:'按次数排序',en:'Order sort'},
        visitNum:{zh:'访问次数',en:'Visits'},
        lastVisit:{zh:'最后访问',en:'Last visit'},
        //推荐分享页
        previewImgBtn:{zh:'预览图片',en:'Preview'},
        saveImgBtn:{zh:'保存图片',en:'Save'},
        shareText1:{zh:'给您推荐了一个优质园区',en:'has recommended a high-quality park to you.'},
        shareText2:{zh:'推荐户型',en:'Recommended Household Type'},
        shareText3:{zh:'元/m²/月起',en:' yuan/m²/month'},
        shareText6:{zh:'预览图片时可长按直接分享给好友或朋友圈',en:'When previewing pictures, you may share them directly with friends or circles of friends.'},
        shareText7:{zh:'分享到朋友圈，附上推荐语更有诚意',en:'Share in the circle of friends, with recommendations more sincere'},
        shareText8:{zh:'可长按直接分享给好友或朋友圈',en:'Share it directly with friends or circles of friends'},
        recommendLang:{zh:'推荐语',en:'Recommendations'},
        copyBtn:{zh:'复制推荐语',en:'Reproductive Recommendations'},
        nextOne:{zh:'换一个',en:'Change another one'},
    },

    //访客预约
    visitor:{
        visitorAppointmentTitle:{zh:'访客预约',en:'Visitor reservation'},
        vRecordTitle:{zh:'预约记录',en:'Appointment record'},
        vName:{zh:'访客姓名',en:'Name'},
        vNamePl:{zh:'请填写来访客户的姓名',en:'Please fill in the name of the visiting customer'},
        vNameTip:{zh:'请输入访客姓名！',en:'Please enter your visitor name!'},
        vPhone:{zh:'访客手机',en:'Cell-phone'},
        vPhonePl:{zh:'请填写手机号码',en:'Please fill in cell phone number'},
        vPhoneTip:{zh:'请输入正确的手机号格式！',en:'Please enter the correct phone number format!'},
        vPlace:{zh:'访客地点',en:'Place'},
        vAddress:{zh:'详细地址',en:'Address'},
        vFloor:{zh:'访问楼层',en:'Floor'},
        vFloorTip:{zh:'请选择访问楼层！',en:'Please choose to access the floor!'},
        vDate:{zh:'预约日期',en:'Date'},
        vDatePl:{zh:'请选择拜访日期',en:'Please select a date of visit'},
        vDateTip:{zh:'请选择拜访日期！',en:'Please choose a date of visit!'},
        vTime:{zh:'预约时间',en:'Time'},
        vTimePl:{zh:'请选择拜访时间',en:'Please select the time of visit'},
        vTimeTip:{zh:'请选择拜访时间！',en:'Please choose a visit time!'},
        carCode:{zh:'车牌号码',en:'Car Number'},
        carCodePl:{zh:'请输入车牌号(非必填)',en:'Please enter the license plate number (not required)'},
        vRecordBtn:{zh:'查看预约记录 >>',en:'View appointment history >>'},
        scanBtn:{zh:'扫一扫 >>',en:'Scan it >>'},
        //详情页增加的字段
        vTitle:{zh:'拜访人/时间',en:'Visitor/time'},
        statusName:{zh:'状态',en:'status'},
        vPlace2:{zh:'拜访地点',en:'Visiting place'},
        enterTime:{zh:'实际到访',en:'Visit time'},
        leaveTime:{zh:'离开时间',en:'Departure time'},
        relName:{zh:'发起人信息',en:'Sponsor information'},
        statusText1:{zh:'已预约',en:'reserved'},
        statusText2:{zh:'已到访',en:'visited'},
        statusText3:{zh:'已离开',en:'leaved'},
        statusText4:{zh:'已失效',en:'expired'},
        affirmVisitorBtn:{zh:'确认到访',en:'Confirm visit'},
        affirmLeaveBtn:{zh:'确认离开',en:'Confirm to leave'},
        //访客成功
        visitorSuccess:{zh:'预约成功！',en:'The appointment is successful!'},
        vDesText:{zh:'您的访客预约信息已发送到：',en:'Your visitor reservation information has been sent to:'},
        vInfoBtn:{zh:'查看预约信息 >>',en:'View appointment information >>'},
    },

    //扫码开门
    scanCode:{
        scanCodeTitle:{zh:'扫码开门',en:'Scan code'},
        scanCodeTip:{zh:'将二维码对准闸机扫描机，即可通行。',en:'Align the QR code with the gate scanner and you will be able to pass.'},
        checkRecordBtn:{zh:'查看历史记录 >>',en:'View history >>'},
        scanSuccessTip:{zh:'扫码成功！',en:'Scanning code is successful!'},
        scanSuccessDes:{zh:'感谢您使用园叮门禁系统',en:'Thank you for using the garden access control system.'},
    },

    //聊天
    chat:{
        title:{zh:'消息中心',en:'Message Center'},
        systemNotice:{zh:'系统公告',en:'Notification'},
        systemDes:{zh:'园区的通知和公告',en:'Notices and announcements of park'},
        message:{zh:'通知消息',en:'Message'},
        mesDes:{zh:'事项的进度消息等',en:'Progress message of the matter, etc.'},
        chating:{zh:'聊天中....',en:'Chatting....'},
        sendBtn:{zh:'发送',en:'Send'},
        otherText:{zh:'[其他]',en:'[other]'},
        loadAll:{zh:'已全部加载完',en:'All loaded'},
    },

    // 服务模块
    serve:{
        //服务首页：serve-index
        title: { zh: '服务', en: '' },
        searchPl: { zh: '请输入关键词', en: '' },
        browseTitle: { zh: '最近浏览', en: '' },
        serveLabel: { zh: '服务', en: '' },
        browseText1: { zh: '用户', en: '' },
        browseText2: { zh: '浏览了', en: '' },
        recommendTitle: { zh: '推荐服务', en: '' },
        salesLabel: { zh: '销量', en: '' },
        salesLabel2:{ zh: '累计销量', en: '' },
        consultLabel: { zh: '咨询', en: '' },
        consultLabel2:{ zh: '累计咨询', en: '' },
        companyTitle: { zh: '我要开公司', en: '' },
        companyDes: { zh: '创业第一步，注册梦想起点', en: '' },
        gysTitle: { zh: '热门服务供应商', en: '' },
        selfsupportLabel: { zh: '自营', en: '' },
        selfsupportLabel2: { zh: '平台自营服务', en: '' },
        attestationLabel: { zh: '平台认证', en: '' },
        serveBtn: { zh: '服务 >', en: '' },
        aboutBtn: { zh: '关于 >', en: '' },
        priceStatus01: { zh: '面议', en: '' },
        priceStatus02: { zh: '定金', en: '' },
        priceStatus03: { zh: '促销', en: '' },
        //服务列表：serve-list
        listTitle: { zh: '服务列表', en: '' },
        tagName01: { zh: '默认排序', en: '' },
        tagName02: { zh: '发布时间', en: '' },
        tagName03: { zh: '咨询量', en: '' },
        tagName04: { zh: '销量', en: '' },
        tagName05: { zh: '价格', en: '' },
        //服务详情：serve-detail
        regionTitle:{ zh: '服务地区', en: '' },
        deadlineTitle:{ zh: '服务期限', en: '' },
        serveDetailTitle:{ zh: '服务详情', en: '' },
        consultBtn:{ zh: '留言咨询', en: '' },
        payOrderBtn:{ zh: '立即下单', en: '' },
        //供应商详情:supplier-detail
        supplierTitle:{ zh: '服务供应商', en: '' },
        supplierDetailTitle01:{ zh: '企业介绍', en: '' },
        supplierDetailTitle02:{ zh: '服务介绍', en: '' },
        supplierDetailTitle03:{ zh: '服务案例', en: '' },
        //供应商列表
        SelectedServices:{ zh: '精选服务', en: 'Selected services' },
        //取消服务
        cancelTitle:{ zh: '取消服务', en: '' },
        causeList:[
            { zh: '不想要这项服务', en: '' },
            { zh: '服务下单后一直没有响应', en: '' },
            { zh: '信息填写错误重新下单', en: '' },
            { zh: '其他原因', en: '' },
        ],
        causeTitle:{ zh: '请选择取消服务的原因：', en: '' },
        causePl:{ zh: '请填写取消服务的原因…', en: '' },
        causeTip:{ zh: '请选择取消原因', en: '' },
        cancelTip:{ zh: '已取消', en: '' },
        userName:{ zh: '用户姓名', en: '' },
        userNamePl:{ zh: '请填写姓名', en: '' },
        //服务分类
        categoryTitle:{ zh: '服务分类', en: '' },
        //服务咨询
        consultTitle:{ zh: '留言咨询', en: '' },
        entCount:{ zh: '企业人数', en: '' },
        entCountPl:{ zh: '请填写企业人数（选填）', en: '' },
        remarkPl:{ zh: '请备注与服务相关的企业信息(100字以内)', en: '' },
        //服务下单
        remarkPl2:{ zh: '需进行物流配送的服务商品请备注配送地址(100字以内)', en: '' },
        payNum:{ zh: '购买数量', en: '' },
        statementText1:{ zh: '提交订单即视为阅读并同意', en: '' },
        statementText2:{ zh: '《园叮服务平台第三方服务声明》', en: '' },
        payTotal:{ zh: '应付总额：', en: '' },
        payment:{ zh: '应付订金：', en: '' },
        payBtn:{ zh: '确认下单', en: '' },
        //服务订单详情
        orderDetailTitle:{ zh: '订单详情', en: '' },
        evaluationTitle:{ zh: '服务评价', en: '' },
        orderNo:{ zh: '订单号', en: '' },
        createTime:{ zh: '下单时间', en: '' },
        confirmTime:{ zh: '确认时间', en: '' },
        deliveryTime:{ zh: '交付时间', en: '' },
        checkTime:{ zh: '完成时间', en: '' },
        cancelTime:{ zh: '取消时间', en: '' },
        cancelBtn:{ zh: '取消服务', en: '' },
        confirmFinishBtn:{ zh: '确认完成', en: '' },
        evaluationBtn:{ zh: '立即评价', en: '' },
        tipPopData:{
            finish:{
                title:{ zh: '服务完成', en: '' },
                des:{ zh: '感谢您对我们的支持！\n本次服务已经完成？', en: '' },
                tipText:{ zh: '已完成', en: '' },
            },
            evaluation:{
                title:{ zh: '服务评价', en: '' },
                des:{ zh: '请为我们的服务评分！', en: '' },
                tipText:{ zh: '已评分', en: '' },
            }
        },
        orderStatus01:{ zh: '待确认', en: '' },
        orderStatus02:{ zh: '待交付', en: '' },
        orderStatus03:{ zh: '待验收', en: '' },
        orderStatus04:{ zh: '待评价', en: '' },
        orderStatus05:{ zh: '已完成', en: '' },
        orderStatus06:{ zh: '已取消', en: '' },
        orderStatus07:{ zh: '取消/售后', en: '' },
        orderStatus08:{ zh: '全部', en: '' },
        //服务订单列表
        orderListTitle:{ zh: '我的服务', en: '' },
        amountMoney:{ zh: '合计金额：', en: '' },
    },

    //待办事项
    backlog:{
        myBacklogTitle: { zh: '我的待办事项', en: '' }
    },

    //户型模块
    house:{
        listTitle: { zh: '户型列表', en: '' },
        detailTitle: { zh: '户型详情', en: '' },
        
        price: { zh: '价格', en: '' },
        area: { zh: '面积', en: '' },
        orientation: { zh: '朝向', en: '' },
        parkName: { zh: '所属园区', en: '' },
        houseDes: { zh: '户型描述', en: '' },
        serveTitle: { zh: '服务及设施', en: '' },
        parkTitle: { zh: '园区简介', en: '' },
        trafficTitle: { zh: '公共交通', en: '' },
        parkBtn: { zh: '进入园区 >', en: '' },
        makePhoneBtn: { zh: '联系园区负责人', en: '' },
    },


     /*------ 组件 ---------*/
    //专家
    cpExpertList:{
        popularityText:{zh:'人气王',en:'Popular king'},
        attentionText:{zh:'人关注',en:' people follow'},
        projectText:{zh:'已指导项目',en:'Guided project '},
        geText:{zh:'个',en:''},
        referText:{zh:'在线咨询',en:'Consultation'},
    },

    //评论
    cpDiscussList:{
        discussTitle:{zh:'大家是怎么说的',en:'What do you say'},
        shareBtn:{zh:'分享',en:'Share'},
        collectBtn:{zh:'收藏',en:'Collection'},
        inputTip:{zh:'我也有话说',en:"Let's make a comment."},
        collectTip:{zh:'已收藏！',en:'collected!'},
        unCollectTip:{zh:'已取消收藏！',en:'Collection has been canceled!'},
        submitTip:{zh:'提交中',en:'submitting'},
    },

    //活动
    cpActivityList:{
        iApply:{zh:'我要报名',en:'Sign up'},
        freeApply:{zh:'免费报名',en:'Free Apply'},
        applyText:{zh:'人已报名',en:' people signed up'},
        status1:{zh:'准备中',en:'preparing'},
        status2:{zh:'报名中',en:'registration'},
        status3:{zh:'待开始',en:'waiting to start'},
        status4:{zh:'进行中',en:'processing'},
        status5:{zh:'已结束',en:'finish'},
        status6:{zh:'已取消',en:'call of'},
        fullPerson:{zh:'已满员',en:'full'},
    },

    //政策
    cpPolicyList:{
        bonusText01:{zh:'直接补贴，最高',en:'Maximum subsidy'},
        bonusText02:{zh:'无',en:''},
        knowBtn:{zh:'了解一下',en:'Know'},
        wanText:{zh:'万',en:''},
    },

    //报修
    cpRepairList:{
        typeName:{zh:'报修类型',en:'Repair type'},
        severScore:{zh:'服务评分',en:'Service rating'},
        noDes:{zh:'暂无描述',en:'No description'},
        payMoney:{zh:'支付金额',en:'Payment amount'},
        callOffBtn:{zh:'确认取消',en:'Cancel'},
        desTip:{zh:'真的要取消报修订单吗？',en:'Do you really want to cancel the amendment?'},
        callOffRepair:{zh:'报修已取消',en:'Repair has been cancelled'},
    },

    //场地
    cpReserveList:{
        reserveBook:{zh:'预定场地',en:'Booking venue'},
        tagName1:{zh:'待确认',en:'Unconfirmed'},
        tagName2:{zh:'已通过',en:'Passed'},
        tagName3:{zh:'已过期',en:'Expired'},
        labelName1:{zh:'待确认',en:'unconfirmed'},
        labelName2:{zh:'待支付',en:'unpaid'},
        labelName3:{zh:'已完成',en:'finish'},
        labelName4:{zh:'已过期',en:'expired'},
    },

    //服务一览表
    cpServePricePop:{
        title:{zh:'有偿服务价格一览表',en:'Paid service price list'},
        cost:{zh:'人工费',en:'Labor fee'},
        unit:{zh:'单位',en:'unit'},
        explainText:{zh:'说明：\n1、未设收费标准项目可商议定价。\n2、上述收费标准中仅指人工费，全部不包含材料费。',en:'Description：\n1、No fee standard items can be negotiated for pricing. \n2、The fee standard refers only to labor costs, and all materials are not included.'},
        iKnowBtn:{zh:'我知道了',en:'I know'},
    },

    //企业提示弹窗
    cpAuditTip:{
        tipText1:{zh:'您已注册成功，部分功能需通过\n企业认证后才可使用',en:'You have successfully registered, some functions have to be passed, and the company can only use it after certification.'},
        tipText2:{zh:'请等待通过认证或联系企业管理员',en:'Please wait for certification or contact the enterprise administrator'},
        iKnowBtn:{zh:'我知道了',en:'I know'},
    },

    //登录弹窗
    cpLoginTip:{
        tipText1:{zh:'您还没有登录园区的账号，登录后可\n享用园区的所有服务！',en:'You have not yet logged in to the campus account, you can enjoy all the services of the park after logging in!'},
        tipText2:{zh:'还没有账号？',en:"Don't have an account yet?"},
        loginBtn:{zh:'立即登录',en:'Login'},
        regBtn:{zh:'快速注册 >>',en:'Registration'},
    },

    //登录弹窗
    cpTab:{
        menuText1:{zh:'首页',en:'Home'},
        menuText2:{zh:'发现',en:'Found'},
        menuText3:{zh:'服务',en:'Services'},
        menuText4:{zh:'我的',en:'User'},
    },

    //待办事项
    cpBacklog:{
        repairText:{zh:'报修',en:'repair'},
        goodsText:{zh:'物资',en:'material'},
        billText:{zh:'账单',en:'order'},
        costText:{zh:'费用',en:'Cost'},
        fixturesText:{zh:'装修',en:'renovation'},
        pending:{zh:'待处理',en:'Pending'},
        buildTip:{zh:'功能建设中，请到后台继续操作',en:'In the process of function construction, please go back to the background and continue to operate.'},
    },

}
